name: Create TAG and send sync request

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Version Changed
        id: check
        run: |
          MAJOR=$(jq -r '.major' version.json)
          MINOR=$(jq -r '.minor' version.json)
          PATCH=$(jq -r '.patch' version.json)
          VERSION_TAG="v$MAJOR.$MINOR.$PATCH"
          CHANGED_FILES=$(git diff --name-only $(git merge-base --fork-point remotes/origin/main || git merge-base remotes/origin/main HEAD))
          if echo "$CHANGED_FILES" | grep -q "version.json" && ! git rev-parse "$VERSION_TAG" >/dev/null 2>&1; then
            echo "should_tag=true" >> test.txt
          else
            echo "should_tag=false" >> test.txt
          fi

      - name: Create TAG
        if: steps.check.outputs.should_tag == 'true'
        run: |
          MAJOR=$(jq -r '.major' version.json)
          MINOR=$(jq -r '.minor' version.json)
          PATCH=$(jq -r '.patch' version.json)
          VERSION_TAG="v$MAJOR.$MINOR.$PATCH"
          git tag "$VERSION_TAG"
          git push origin "$VERSION_TAG"

      - name: Send Sync Request
        if: steps.check.outputs.should_tag == 'true'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/actions/workflows/:workflow_id/dispatches
          owner: damianw27
          repo: repo1
          workflow_id: synchronize-with-repo2.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          
       
          
