name: Send Sync Request On Release

on:
  release:
    types: [created]

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Send Sync Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO1_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/damianw27/repo1/actions/workflows/synchronize-with-repo2.yml/dispatches \
            -d '{"ref":"main"}'
          
       
          
